# Generated by Django 5.0.2 on 2025-12-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkartapp', '0002_users_is_active_users_is_admin_users_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_joined'),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='last_name'),
        ),
    ]
