# Generated by Django 5.0.2 on 2025-12-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkartapp', '0003_users_date_joined_users_email_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
