# Generated by Django 5.0.2 on 2025-12-10 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkartapp', '0004_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_login'),
        ),
        migrations.CreateModel(
            name='GeneratedAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='modified_date')),
                ('token', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
